### ISSUE TITLE
knife emoji is broken

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-markdown-emoji#11]
The `:knife:` emoji displays a broken image icon.

When visiting the URL https://s3.amazonaws.com/habitica-assets/cdn/emoji/knife.png you see:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1027003EF6ED2A97</RequestId>
<HostId>
Y5MJHwMUeYiz84g80mE9/ydA/6OdgM4H5/4l5xqS1d92PQpHUuvqdT/qTfx7y/WP
</HostId>
</Error>
```

**Comment by crookedneighbor** [comment]
Hmmm, that image was missing for some reason. Uploaded now.

**Comment by crookedneighbor** [comment]
Okay, I see. The previous emoji lib we used, where I got all the icons, didn't include images for duplicate emojis. So it didn't include knife, because it had hocho and would substitute when needed. This will be a problem for any emoji in this list with two or more options (separated by a slash) https://github.com/iamcal/emoji-data/blob/29345e97c6bfa58fe9565ad7d2795de8c236d3c6/build/data_emoji_names.txt
